### ISSUE TITLE
If summary cannot be scraped it remains empty, but filling it is required to close out form

### ISSUE THREAD

**Issue by b-a0** [digitaldutch/roaddanger.org#11]
Example URL: https://regio15.nl/nieuws/ongevallen/36619/wegvervoer-ongeval-letsel-neherkade-2980-den-haag/

Steps to reproduce:
1. Go to https://nl.roaddanger.org/
2. Add new article via `+` sign in the upper right
3. Add this URL: https://regio15.nl/nieuws/ongevallen/36621/spoorvervoer-ongeval-letsel-scheveningseweg-den-haag-lijn-1/ and press on "Artikel ophalen"
4. Note that the "Samenvatting" field remains empty, it cannot be scraped for this URL
5. Fill in the "Tekst" field under "Ongeluk" to create a manual summary
6. Fill in the rest of the fields ("Datum", "Betrokken mensen", "Locatie", etc...)
7. Press "Opslaan"

Expected result: the article is saved and text from the "Tekst" field is used as the summary.

Actual result: error message is shown with the text: "Artikel samenvatting niet ingevuld".

Workaround: in the browser inspector I can remove the `data-readonlyhelper` attribute of the `editArticleText` element and paste in my own summary, then I can save it. But this quite cumbersome.

**Comment by b-a0** [comment]
Now found that this only occurs after the "Opslaan" button is pressed (the first time). Before that the summary field is editable and I can place text there manually (e.g. just after step 4).

**Comment by digitaldutch** [comment]
There were two text fields: One for the crash and one for the article. Now when adding a new crash only the article text field is visible which should make this less confusing.
