### ISSUE TITLE
Data export seems incomplete, limited at 10000 crashes

### ISSUE THREAD

**Issue by b-a0** [digitaldutch/roaddanger.org#12]
Sorry, another issue... (I think).

It seems as if not all data is exported in the gzip JSON file.

When exporting the data via https://nl.roaddanger.org/export/ I get:
- a gzip JSON file [`roaddanger_org_data_all_text.json.gz`](https://github.com/digitaldutch/roaddanger.org/files/14564484/roaddanger_org_data_all_text.json.gz) (about 4.66 MB)
- ater extraction I have [`roaddanger_org_data_all_text.json`](https://github.com/digitaldutch/roaddanger.org/files/14564477/roaddanger_org_data_all_text.json) (about 20.31 MB)
- counting the items in that JSON using `jq length .\roaddanger_org_data_all_text.json` I get 10000 items

However, when I visit https://nl.roaddanger.org/statistics/general I see there are approximately 14k crashes (this corresponds with the current crash ID's):

![image](https://github.com/digitaldutch/roaddanger.org/assets/25707742/393bb9b2-f2af-485f-a4d5-84743508c072)

Due to the neat amount of 10000 items I suspect there is some limiting going on. I don't know PHP, but the [export function](https://github.com/digitaldutch/roaddanger.org/blob/80b6c320bfef058457990236965d36d857041f14/admin/exportdata.php#L27) does mention `$maxRows = 10000;` and this variable [is used later in the SQL query](https://github.com/digitaldutch/roaddanger.org/blob/80b6c320bfef058457990236965d36d857041f14/admin/exportdata.php#L72). Could this be the culprit?

**Comment by digitaldutch** [comment]
This is fixed in latest version. There is an artificial limit. It has now been set to 100,000 crashes for the export.
