### ISSUE TITLE
Add new transportation mode "speed pedelec"

### ISSUE THREAD

**Issue by OliNau** [digitaldutch/roaddanger.org#6]
Hello,

It would be helpful if there would be a new transportation mode "speed pedelec"/"high speed e-bike". I think this could be a valuable addition because:
1. They sometimes get a bad reputation of being dangerous because they, in Belgium at least, are oftentimes allowed to make use of the cycle path, which is often not build with the higher average speed of the pedelec in mind. It would be interesting to see data about how often they are involved in an accident vs. a "normal" bicycle.

2. Currently it is not clear how they should be categorised. Some instances view them as mopeds (for example the Belgian traffic code), while other see them as bicycles (for example the Flemish citizen science project [Straatvinken](https://straatvinken.be/)). It is not good for the data if in some collisions the speed pedelecs involved are categorised as bicycles and other as mopeds.

In my humble opinion, a new category would be very helpful.
An other possibility would be to classify the pedelec as a bicycle or a moped and then changing the name of the category to bicycle/pedelec for example so it is clear where they need to be placed.

Thank you very much!

**Comment by digitaldutch** [comment]
We have discussed this and there are a few issues that stop us from adding the category. The media source often does not mention if a bike is a normal, an electric of a speed pedelec. And we don't want too many categories as it makes it harder to enter the data. I do agree that sometimes categories get mixed up. Is a souped-up fat bike a moped or a bike. It's not perfect as it is now, but we have to do with it.

**Comment by OliNau** [comment]
Just a short reply: In Belgium they are a separate category and are more often than not mentioned in news papers, for example:
https://www.hbvl.be/cnt/dmf20230927_92076642 
https://www.gva.be/cnt/dmf20240325_92890463
https://www.hln.be/turnhout/man-60-met-speed-pedelec-levensgevaarlijk-gewond-na-botsing-met-voetganger~a5e816f5/
https://www.gva.be/cnt/dmf20210624_92686241
https://www.vrt.be/vrtnws/nl/2021/05/28/dodelijk-ongeval-met-speed-pedelec-man-botst-tegen-aanhangwagen/

They are also counted separately in the official road accident statistics: https://www.vias.be/publications/Statistich%20rapport%202022%20-%20Verkeersongevallen%202021/stat_report_2021_NL_FINAL.pdf 

But if you prefer to not add the category, could we get some guidance on how to map them? Should they be categorised as moped (like is written in de Belgium traffic code) or should they be added as bicycles (like they are often viewed as)?

**Comment by digitaldutch** [comment]
I checked and we currently have just 5 crashes with *pedelec* in the database.

https://www.roaddanger.org/?search=*pedelec*&country=UN&period=all&hd=1&hi=1

The good news is that you can already filter on any word. If you add *pedelec* in the search field you will view them. You can even do that on the counterparty graph:
https://www.roaddanger.org/statistics/counterparty?period=all&country=UN&search=*pedelec*

As you say the categories are merging with the electrification of transport. mopeds get electric, speedpedelecs are sort of the new mopeds as are some fat bikes. An idea is to change the moped category into moped/speedpedelec. They are more of less going the same speed. Although mopeds are generally heavier.
